### ISSUE TITLE
Ensure we're doing the right thing w/ "Something went wrong / not enough information" responses

### ISSUE THREAD

**Issue by rlvoyer** [socrata/arcs#8]
One of the choices we give our workers, is "Something went wrong / not enough information". We need to exclude these judgments from our NDCG calculation. We should also report these.

@kavedder @rlvoyer

**Comment by rlvoyer** [comment]
Looks like we're already handling these correctly.

https://github.com/socrata/arcs/blob/initial_checkin/arcs/download_crowdflower.py#L60

**Comment by kavedder** [comment]
:smile:
